DROP TABLE events CASCADE CONSTRAINTS;
-- DROP TABLE events;
DROP TABLE participants CASCADE CONSTRAINTS;
-- DROP TABLE participants; 

CREATE TABLE events (
  event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_title VARCHAR2(255) NOT NULL,
  event_description CLOB,
  event_organizer_id NUMBER NOT NULL,
  event_start_date DATE NOT NULL,
  event_start_time VARCHAR2(20) NOT NULL,
  event_end_time VARCHAR2(20) NOT NULL,
  event_location VARCHAR2(255),
  event_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (event_organizer_id) REFERENCES users(id)
);

CREATE TABLE participants (
  participant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  participant_event_id NUMBER NOT NULL,
  participant_user_id NUMBER NOT NULL,
  participant_joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (participant_event_id) REFERENCES events(event_id),
  FOREIGN KEY (participant_user_id) REFERENCES users(id)
);

-- INSERT INTO events (event_title, event_description, event_organizer_id, event_start_date, event_start_time, event_end_time, event_location) 
-- VALUES ('Tech Conference 2023', 'A conference about the latest in technology.', 1, TO_DATE('2023-11-15', 'YYYY-MM-DD'), '09:00 AM', '05:00 PM', 'San Francisco');

-- INSERT INTO events (event_title, event_description, event_organizer_id, event_start_date, event_start_time, event_end_time, event_location) 
-- VALUES ('Art Expo 2023', 'An exhibition showcasing modern art.', 1, TO_DATE('2023-12-01', 'YYYY-MM-DD'), '10:00 AM', '06:00 PM', 'Los Angeles');


select * from events;